spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/time_task_tracking_tool_db
    username: postgres
    password: postgreSQL17
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
